[package]
name = "vicky"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.19"
jomini = "0.21.2"
serde = "1.0.130"

[dev-dependencies]
mockall = "0.11.2"
tempfile = "3"
rstest = "0.17.0"